dist: xenial
language: cpp

branches:
  only:
    - master

cache:
  apt: true

matrix:
  include:
    - name: "CONFIG_ARG=\"--with-tls=gnutls --with-regex=posix --with-migemo\""
      os: linux
      compiler: gcc
      env: CONFIG_ARG="--with-tls=gnutls --with-regex=posix --with-migemo"
      addons:
        apt:
          update: true
          packages:
            - autoconf-archive
            - libgtkmm-3.0-dev
            - zlib1g-dev
            - libgnutls28-dev
            - libmigemo-dev

    - name: "CONFIG_ARG=\"--with-tls=openssl --with-regex=pcre --with-alsa --with-compat-cache-dir\""
      os: linux
      compiler: gcc
      env: CONFIG_ARG="--with-tls=openssl --with-regex=pcre --with-alsa --with-compat-cache-dir"
      addons:
        apt:
          update: true
          packages:
            - autoconf-archive
            - libgtkmm-3.0-dev
            - zlib1g-dev
            - libssl-dev
            - libpcre3-dev
            - libasound2-dev

    - name: "CONFIG_ARG=\"--with-tls=gnutls --with-regex=oniguruma --with-sessionlib=no --with-pangolayout\""
      os: linux
      compiler: gcc
      env: CONFIG_ARG="--with-tls=gnutls --with-regex=oniguruma --with-sessionlib=no --with-pangolayout"
      addons:
        apt:
          update: true
          packages:
            - autoconf-archive
            - libgtkmm-3.0-dev
            - zlib1g-dev
            - libgnutls28-dev
            - libonig-dev

install:
  - travis_retry git clone --depth 1 --branch master https://github.com/google/googletest.git test/googletest

script:
  - autoreconf -i
  - ./configure $CONFIG_ARG
  - make -j$(nproc)
  - make test -j$(nproc)
  - ./src/jdim -V
