// カラーID

#ifndef _COLOR_ID_H
#define _COLOR_ID_H

enum
{
    COLOR_DEFAULT = 0,
    COLOR_CHAR,
    COLOR_CHAR_NAME,   
    COLOR_CHAR_SELECTION,
    COLOR_CHAR_LINK,
    COLOR_CHAR_LINK_PUR, // パープル
    COLOR_CHAR_LINK_RED,    
    COLOR_CHAR_HIGHLIGHT,
    COLOR_CHAR_BOOKMARK,
    
    COLOR_BACK,
    COLOR_BACK_SELECTION,
    COLOR_BACK_HIGHLIGHT,

    COLOR_SEPARATOR_NEW, // 新着セパレータ

    COLOR_IMG_NOCACHE,
    COLOR_IMG_LOADING,
    COLOR_IMG_CACHED,
    COLOR_IMG_ERR,
    
    COLOR_NUM
};

#endif
