# SPDX-License-Identifier: FSFAP
name: jdim
adopt-info: jdim
license: "GPL-2.0"

confinement: strict
base: core22
grade: stable
icon: jdim.png

# https://snapcraft.io/gnome-42-2204
# Snap Store does not provide gnome-42-2204 package for i386, ppc64el and s390x
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64
  - build-on: armhf
    build-for: armhf
  - build-on: riscv64
    build-for: riscv64

# https://snapcraft.io/docs/gnome-extension
parts:
  jdim:
    plugin: meson
    source: https://github.com/JDimproved/JDim.git
    source-type: git
    source-branch: master
    source-depth: 1
    meson-parameters:
      # Use dpkg-buildflags to set compiler flags instead of meson options
      - --buildtype=plain
      - --prefix=/
      - --strip
      - -Dbuild_tests=disabled
      - -Dcompat_cache_dir=disabled
      - -Dpangolayout=enabled
      - "-Dpackager=Snap (JDimproved project)"
    build-environment:
      # https://wiki.debian.org/Hardening
      - DEB_BUILD_MAINT_OPTIONS: "hardening=+all"
      # Use -isystem to suppress compiler warning:
      # /snap/gnome-42-2204-sdk/current/usr/include/limits.h:124:3: warning: #include_next is a GCC extension
      - CPPFLAGS: "$(dpkg-buildflags --get CPPFLAGS) -isystem /snap/gnome-42-2204-sdk/current/usr/include"
      - CXXFLAGS: "$(dpkg-buildflags --get CXXFLAGS)"
      - LDFLAGS: "$(dpkg-buildflags --get LDFLAGS)"
    override-build: |
      set -eu
      craftctl default
      VER="$(${CRAFT_PART_INSTALL}/bin/jdim -V | sed -n -e '1s%^[^0-9]*\([^-]\+\)-\([^(]\+\)(git:\([0-9a-f]\+\).*$%\1-\2-\3%p')"
      echo "version ${VER}"
      craftctl set version="${VER}"
    override-prime: |
      set -eu
      craftctl default
      sed --in-place -e 's|^Icon=.*|Icon=\${SNAP}/share/icons/hicolor/48x48/apps/jdim.png|' \
      ${CRAFT_PRIME}/share/applications/jdim.desktop
    parse-info: [share/metainfo/jdim.metainfo.xml]

apps:
  jdim:
    command: bin/jdim
    common-id: com.github.jdimproved.jdim
    desktop: share/applications/jdim.desktop
    extensions: [gnome]
    plugs:
      - home
      - network
