name: jdim
adopt-info: jdim
license: "GPL-2.0"

confinement: strict
base: core18
grade: stable
icon: jdim.png

# https://forum.snapcraft.io/t/gtk3-applications/13483
parts:
  jdim:
    plugin: autotools
    source: https://github.com/JDimproved/JDim.git
    source-type: git
    source-branch: master
    source-depth: 1
    configflags:
      - --disable-compat-cache-dir
      - --with-gtkmm3
      - --with-pangolayout
      - --with-xdgopen
    build-environment:
      # https://wiki.debian.org/Hardening
      - CFLAGS: "$(dpkg-buildflags --get CFLAGS)"
      - CPPFLAGS: "$(dpkg-buildflags --get CPPFLAGS)"
      - CXXFLAGS: "$(dpkg-buildflags --get CXXFLAGS)"
      - LDFLAGS: "$(dpkg-buildflags --get LDFLAGS)"
    build-packages:
      # https://packages.ubuntu.com/source/focal/jdim
      - libgnutls28-dev
      - libgtkmm-3.0-dev
      - zlib1g-dev
      - autoconf-archive
    override-build: |
      set -eu
      snapcraftctl build
      strip -s ${SNAPCRAFT_PART_INSTALL}/bin/jdim
      VER="$(./src/jdim -V | sed -n -e '1s%^[^0-9]*\([^-]\+\)-\([^(]\+\)(git:\([0-9a-f]\+\).*$%\1-\2-\3%p')"
      echo "version ${VER}"
      snapcraftctl set-version "${VER}"
    override-prime: |
      set -eu
      snapcraftctl prime
      sed --in-place -e 's|^Icon=.*|Icon=\${SNAP}/share/icons/hicolor/48x48/apps/jdim.png|' \
      ${SNAPCRAFT_PRIME}/share/applications/jdim.desktop
    parse-info: [jdim.metainfo.xml]

  # gnome-3-28 extension does not bundle shared objects for C++ library.
  jdim-depends:
    plugin: nil
    stage-packages:
      # Exclude packages provided by gnome-3-28 extension and core18.
      # https://gitlab.gnome.org/Community/Ubuntu/gnome-3-28-1804/blob/master/snapcraft.yaml
      - libatkmm-1.6-1v5
      - libcairomm-1.0-1v5
      - libfribidi0
      - libglibmm-2.4-1v5
      - libgtkmm-3.0-1v5
      - libpangomm-1.4-1v5
      - libpcre2-8-0
      - libsigc++-2.0-0v5

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.github.jdimproved.JDim

apps:
  jdim:
    command: bin/jdim
    common-id: com.github.jdimproved.JDim
    desktop: share/applications/jdim.desktop
    # https://forum.snapcraft.io/t/the-gnome-3-28-extension/13485
    extensions: [gnome-3-28]
    plugs:
      - gsettings
      - home
      - network
      - unity7
    slots:
      - dbus-daemon
    command-chain:
      - snap/command-chain/desktop-launch
