name: jdim
adopt-info: jdim
license: "GPL-2.0"

confinement: strict
base: core18
grade: stable
icon: jdim.png

# for i386 and testing amd64
architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: i386
    run-on: i386

# https://forum.snapcraft.io/t/gtk3-applications/13483
parts:
  jdim:
    plugin: meson
    source: https://github.com/JDimproved/JDim.git
    source-type: git
    source-branch: master
    source-depth: 1
    meson-parameters:
      # Use dpkg-buildflags to set compiler flags instead of meson options
      - --buildtype=plain
      - --prefix=/
      - -Dbuild_tests=disabled
      - -Dcompat_cache_dir=disabled
      - -Dpangolayout=enabled
    build-environment:
      # https://wiki.debian.org/Hardening
      - CFLAGS: "$(dpkg-buildflags --get CFLAGS)"
      - CPPFLAGS: "$(dpkg-buildflags --get CPPFLAGS)"
      - CXXFLAGS: "$(dpkg-buildflags --get CXXFLAGS)"
      - LDFLAGS: "$(dpkg-buildflags --get LDFLAGS)"
    build-packages:
      # https://packages.ubuntu.com/source/focal/jdim
      - libgnutls28-dev
      - libgtkmm-3.0-dev
      - zlib1g-dev
    override-build: |
      set -eu
      snapcraftctl build
      strip -s ${SNAPCRAFT_PART_INSTALL}/bin/jdim
      VER="$(${SNAPCRAFT_PART_INSTALL}/bin/jdim -V | sed -n -e '1s%^[^0-9]*\([^-]\+\)-\([^(]\+\)(git:\([0-9a-f]\+\).*$%\1-\2-\3%p')"
      echo "version ${VER}"
      snapcraftctl set-version "${VER}"
    override-prime: |
      set -eu
      snapcraftctl prime
      sed --in-place -e 's|^Icon=.*|Icon=\${SNAP}/share/icons/hicolor/48x48/apps/jdim.png|' \
      ${SNAPCRAFT_PRIME}/share/applications/jdim.desktop
    parse-info: [jdim.metainfo.xml]

  # gnome-3-28 extension does not bundle shared objects for C++ library.
  jdim-depends:
    plugin: nil
    stage-packages:
      # Exclude packages provided by gnome-3-28 extension and core18.
      # https://gitlab.gnome.org/Community/Ubuntu/gnome-3-28-1804/blob/master/snapcraft.yaml
      - libatkmm-1.6-1v5
      - libcairomm-1.0-1v5
      - libfribidi0
      - libglibmm-2.4-1v5
      - libgtkmm-3.0-1v5
      - libpangomm-1.4-1v5
      - libsigc++-2.0-0v5
    prime:
      - -./etc
      - -./lib
      - -./usr/bin
      - -./usr/sbin
      - -./usr/share
      - -./var
      # Include shared objects for C++ library and a few missings.
      - ./usr/lib/**/libatkmm-1.6.so*
      - ./usr/lib/**/libcairomm-1.0.so*
      - ./usr/lib/**/libfribidi.so*
      - ./usr/lib/**/libgdkmm-3.0.so*
      - ./usr/lib/**/libgiomm-2.4.so*
      - ./usr/lib/**/libglibmm-2.4.so*
      - ./usr/lib/**/libglibmm_generate_extra_defs-2.4.so*
      - ./usr/lib/**/libgtkmm-3.0.so*
      - ./usr/lib/**/libpangomm-1.4.so*
      - ./usr/lib/**/libsigc-2.0.so*

apps:
  jdim:
    command: bin/jdim
    common-id: com.github.jdimproved.JDim
    desktop: share/applications/jdim.desktop
    # https://forum.snapcraft.io/t/the-gnome-3-28-extension/13485
    extensions: [gnome-3-28]
    plugs:
      - gsettings
      - home
      - network
