name: jdim
adopt-info: jdim
license: "GPL-2.0"

confinement: strict
base: core18
grade: stable
icon: jdim.png

# https://snapcraft.io/blog/gnome-3-34-snapcraft-extension
parts:
  jdim:
    plugin: meson
    source: https://github.com/JDimproved/JDim.git
    source-type: git
    source-branch: master
    source-depth: 1
    meson-parameters:
      # Use dpkg-buildflags to set compiler flags instead of meson options
      - --buildtype=plain
      - --prefix=/
      - -Dcompat_cache_dir=disabled
      - -Dpangolayout=enabled
      - -Dregex=glib
    build-environment:
      # https://wiki.debian.org/Hardening
      # Use -isystem to suppress compiler warning:
      # /snap/gnome-3-34-1804-sdk/current/usr/include/limits.h:124:3: warning: #include_next is a GCC extension
      - CPPFLAGS: "$(dpkg-buildflags --get CPPFLAGS) -isystem /snap/gnome-3-34-1804-sdk/current/usr/include"
      - CXXFLAGS: "$(dpkg-buildflags --get CXXFLAGS)"
      - LDFLAGS: "$(dpkg-buildflags --get LDFLAGS)"
    build-packages:
      - build-essential
      - git
      - libgnutls28-dev
      - libsigc++-2.0-dev
    stage-packages:
      # base or gnome-3-34 extension do not include the follow package:
      - libsigc++-2.0-0v5
    override-build: |
      set -eu
      snapcraftctl build
      strip -s ${SNAPCRAFT_PART_INSTALL}/bin/jdim
      VER="$(${SNAPCRAFT_PART_INSTALL}/bin/jdim -V | sed -n -e '1s%^[^0-9]*\([^-]\+\)-\([^(]\+\)(git:\([0-9a-f]\+\).*$%\1-\2-\3%p')"
      echo "version ${VER}"
      snapcraftctl set-version "${VER}"
    override-prime: |
      set -eu
      snapcraftctl prime
      sed --in-place -e 's|^Icon=.*|Icon=\${SNAP}/share/icons/hicolor/48x48/apps/jdim.png|' \
      ${SNAPCRAFT_PRIME}/share/applications/jdim.desktop
    parse-info: [jdim.metainfo.xml]

apps:
  jdim:
    command: bin/jdim
    common-id: com.github.jdimproved.JDim
    desktop: share/applications/jdim.desktop
    extensions: [gnome-3-34]
    plugs:
      - home
      - network
